### PR TITLE
Add Spanish Translations

### PR DESCRIPTION
**Pull request by patrickdemers6**
Contributes to #56.

All text in the application has been extracted to `/website/lang/`.

Right now, I'm starting translations out with just Spanish.

I'm not sure of the "best way" to organize the language files so I did it based on location in the application and named based on what the text is.

One odd case that I experienced: in the MapPopup, it is created in a new Vue instance. This doesn't have access to the i18n plugin; therefore, I had to pass the needed data in to the component.

## Url Format
- English: '/*'
- Spanish '/en/*'

### CODE REVIEW

**Comment by patrickdemers6** [comment]
Alright, I think I've gotten this to a good state! The sooner we can review this the better. It is very difficult keeping this in line with main since every file has a lot of changes!

**Comment by MoralCode** [comment]
> I'm not sure of the "best way" to organize the language files so I did it based on location in the application and named based on what the text is.

from what i can tell, the standard convention for doing things like this is to use the language code, rather than the full name - i.e. `en` for english and (i think) `es` for spanish. while i dont know the name of this standard i think every language has a code (i.e. german is `de` i think) and that seems to be what other apps use for naming their localization files.

**Comment by patrickdemers6** [comment]
@MoralCode updated to that standard.

**Comment by patrickdemers6** [comment]
@lawrencek1992 state names are the same in spanish, correct?

**Comment by patrickdemers6** [comment]
@GUI this is ready to go!

**Comment by lawrencek1992** [comment]
> @lawrencek1992 state names are the same in spanish, correct?

Just saw this question. Yes they usually are. Pronounced differently but spelled the same is fine. There are Spanish versions for SOME names, like you could say "Nuevo Jersey" instead of "New Jersey," but it's not necessary to change it, in my opinion, because 
1) Most states do NOT have a translation (Alabama, Alaska, Arizona, etc etc). 
2) Even for the ones that technically can be translated, most of the time Spanish speakers just use the English name when speaking. No one will be confused by "New Jersey" or "New York" in place of "Nuevo Jersey" or "Nuevo York," including recent immigrants to the country.

**Comment by GUI** [comment]
@patrickdemers6: This is great! Thanks so much!! I want to play around with this a bit, but having all these translations is a a huge help. I'll try to get this merged in soon this week. But in the meantime, don't feel like you need to be playing catch up with other changes in `main` this week (and sorry if you've already been doing that!). I know we don't want things to diverge more, so I'll try to get this merged in soon, but I can try to deal with any missing text or text tweaks whenever I merge this, so don't feel like you need to be stalking the `main` branch in the meantime. But I really appreciate you getting this all up to speed! Thanks!

**Comment by patrickdemers6** [comment]
Awesome! Just let me know if there's anything else you need from me or you have any questions.

**Comment by shirubana** [comment]
@patrickdemers6  well I apparently don't know how to github either. I have some updates for the spansih translation based on this PR, but could not able to figure out how to push it so now its a branch. Ideas?

**Comment by patrickdemers6** [comment]
@shirubana I believe since you forked GUI's repo, you aren't able to merge with mine. The PR here is from my fork. I believe you need to fork mine which allows me to accept a PR into my fork. Once I accept, it gets added to this PR.

@GUI is this the proper flow for something like this?

**Comment by shirubana** [comment]
@patrickdemers6 I followed your instructions and you should have a PR to your fork now.

**Comment by GUI** [comment]
Apologies this took so long to merge in, but this is finally live! A big thank you to everyone involved!

@patrickdemers6: Thanks so much for doing all of the heavy lifting here!!

@shirubana: I've also picked up your changes and merged them in. Thank you!

There have been a few text changes since the translations were originally done, so there are few things that don't have translations. I'll see if I can get a better translation workflow setup, but in the meantime, if anyone wants to help fill in missing translations, you can search for `: null` in this file to find the missing ones: https://github.com/GUI/covid-vaccine-spotter/blob/main/website/lang/es.json

I actually ended up changing the implementation a tad so the workflow is slightly more gettext-like, where all of the keys are the English text. Otherwise, my personal experience with translated projects is that it's easy for the text to get out of sync (but if the keys are English, then if those change, then it's a good flag that the translations need revisiting; [this post](https://translation.io/blog/gettext-is-better-than-rails-i18n) also summarizes reasons I also like the gettext approach). Hopefully this shouldn't make too much of a difference to anyone else, but just wanted to explain some of the changes if anyone's looking in `main`.

**Pull request merged**
