### PR TITLE
Attempt to make it easier to setup

### PR DESCRIPTION
**Pull request by sigmavirus24**
Hi there,

I'm not a node developer but have found vaccinespotter.org to be super helpful. I noticed you felt the setup was clunky so I tried to automate some of it. This is a first pass. If this is something you're interested in, we can invest more in it and have it download all of the states, etc.

### CODE REVIEW

**Comment by GUI** [comment]
Thank you! This week has gotten the best of me, so sorry I'm slow in reviewing and merging this (among other things), but I'm really trying to get to all these PRs this week. But in the meantime, just wanted to say thank you!

**Comment by patrickdemers6** [comment]
Would it be beneficial to make it so a user can pass in multiple states at once?

**Comment by patrickdemers6** [comment]
Actually this looks nearly identical to #42

**Comment by MetricMike** [comment]
I'd also suggest #42 instead, but it would be nice to have the ability to only setup a single or subset of states like this does (i.e., a DC/MD/VA or NY/NJ/PA setup instead of a national one).

**Comment by sigmavirus24** [comment]
> Would it be beneficial to make it so a user can pass in multiple states at once?

I thought so but wanted to keep it fairly 1:1 with the docs as they are today and then expand from there. I suspect #42 is better for downloading the data as one doesn't need to worry about Windows for development with bash. That said, I think it's still good to have some way of verifying Node and Yarn are installed

**Comment by GUI** [comment]
@sigmavirus24: Sorry for not getting to this sooner! I just merged in #42, so apologies if my delays led to some duplicate efforts. You make great points about some of the extra checks this PR does, but I guess due to the potential for Windows issues you pointed out, and since the overall download size (even for all 50 states) isn't huge, I may stick with the changes made in #42 instead. But I really appreciate you taking the time to figure out the development environment and get all this setup! Thank you!

**Pull request closed without merging**
