### PR TITLE
Add docker-compose to simplify backend development

### PR DESCRIPTION
**Pull request by mkokotovich**
It seems like the backend sides of things were a little more difficult to develop and test, hopefully this helps.

Open to suggestions, and if I get time I might add the ability to run more of the tasks.

### CODE REVIEW

**Comment by GUI** [comment]
Thanks so much! Sorry I’ve been belated in reviewing things, but I’ll try to get to this tomorrow! This will be great to have, though!

**Comment by racedale** [comment]
This seems like it would make the biggest improvement towards allowing others to contribute on the backend

**Comment by jhsu802701** [comment]
It looks like the conflict in the src/runTask.js script is holding things up.  Will this be addressed, or should I start a new branch and pull request to Dockerize this app?

**Comment by mkokotovich** [comment]
I could resolve the conflict, but the PR has sat for a long time without conflicts. I'm not sure how much time @GUI has to review things right now.

**Comment by GUI** [comment]
@mkokotovich: Woot! Thanks so much! This is now merged. I did make some small tweaks based on how I typically work in Docker dev environments in 47c74722caefdb49160a3d23693b9ddc2bd665ae. But let me know if you have feedback or suggestions on my tweaks. But thanks so much for getting all of this setup, this is a huge help!

**Comment by mkokotovich** [comment]
Great, thanks! Your changes to the volumes are much cleaner than what I had, I like it!

**Pull request merged**
