### PR TITLE
Add Publix refresh handler (and bin)

### PR DESCRIPTION
**Pull request by bblack**
Hello from Publix country!

https://github.com/GUI/covid-vaccine-spotter/issues/31

What else is needed to complete Publix pharmacy working here? 

I can't confirm it's working, mostly because I can't get my database set up. Migrations fail because I don't have the postgis extension. On MacOS, I'm running postgres 12 for work. Since the latest is 13, `brew install postgis` succeeds, but installs the version of postgis for pg 13, which doesn't work with pg 12.

### CODE REVIEW

**Comment by mkokotovich** [comment]
Hi, if you look at my pr and either merge it in or just take parts of it, you should be able to get a working database to test against: https://github.com/GUI/covid-vaccine-spotter/pull/64

**Comment by GUI** [comment]
Thank you! Publix would be great to add. @bblack, do you have any sense of how accurate these county level listings are? I had started to look at Publix a while back, but haven’t had a chance to revisit it. If we could rely on these simple county level text files, that would obviously be super quick and easy to update from. I thought when I was originally poking around at this though, it seemed like these lists might lag real appointment availability once you go further into the appointment booking process (eg, this text file would say there were appointments available in a county, but then nothing actually was). But I can’t quite remember if this was the case, or I’m might be mixing this up with another provider. In any case, I think this could still be useful, but just curious if you had any experience or knowledge with how accurate this info might be.

**Comment by bblack** [comment]
> it seemed like these lists might lag real appointment availability once you go further into the appointment booking process

Actually, I hadn't realized there was any further information on their website, because if you select [Georgia](https://www.publix.com/covid-vaccine/georgia), or [South Carolina](https://www.publix.com/covid-vaccine/south-carolina), then you merely see the county-level data (which are all versions of "no availability") and a message like:

> All available COVID-19 vaccine appointments have been claimed. 

But now I've clicked around Florida a bit, and it looks pretty accurate. The biggest problem is that you can't get any data finer than percent-per-county without specifying a single store and completing recaptcha. Once you do that, there are a few possible outcomes:

* a request is made, the response of which tells the page to say "No appointments available" for that store
* a request is made (e.g. `GET https://rx.publix.com/en/f/s/store/appt/1173?eid=181` for store 1173), the response of which is presumably a list of time slots (although I couldn't find any stores that returned more than a single available time slot)
* a request is made (e.g. `POST https://rx.publix.com/en/f/s/appt/autoreserve?eid=181`), which apparently selects and claims a time slot (the page says for 20 minutes)

If we could make that GET request, then we'd have the time slots available for a given store. I've pared it down to:

```
curl 'https://rx.publix.com/en/f/s/store/appt/<store_number>?eid=181' \
  -H '__RequestVerificationToken: <...>' \
  -H 'Cookie: __RequestVerificationToken=<...>; akavpau_VP_RX_db52e60931a8=<...>;' \
  --compressed
```

Presumably the __RequestVerificationToken header and cookie come from the recaptcha; I'm not sure what the other cookie is but it seems necessary.

**Comment by bblack** [comment]
If we could get the list of Publix stores, along with what county and state each one is in, then we could at least determine which stores have _no_ availability due to the entire county having no availability.

**Comment by mbshark** [comment]
Pulling from the press releases: https://corporate.publix.com/about-publix/newsroom/news-releases
Most recent PDFs [FL](https://cutpcdnwimages.azureedge.net/-/media/documents/corporate/fl_covid19_vaccines_02-25-21-3pm.pdf?la=en&hash=4B61E4BE9760F47FB2D98DC329BD8FD76D0C7681) [GA](https://cutpcdnwimages.azureedge.net/-/media/documents/corporate/ga_covid19_vaccines_03-15-21.pdf?la=en&hash=9514A7FA4C644387360F8E61300F2151D3B39FFC) [SC](https://cutpcdnwimages.azureedge.net/-/media/documents/corporate/sc_covid19_vaccines_03-15-21.pdf?la=en&hash=1089924C2896307A4D2541D6CD7114A87A0D32EF)


I was able to use onlineocr.net to pull info from the pdf into excel files and got rid of the extraneous and empty cells 
[001_FL_COVID19_Vaccines_02-25-21-3pm.xlsx](https://github.com/GUI/covid-vaccine-spotter/files/6154218/001_FL_COVID19_Vaccines_02-25-21-3pm.xlsx)
[002_SC_COVID19_Vaccines_03-15-21.xlsx](https://github.com/GUI/covid-vaccine-spotter/files/6154219/002_SC_COVID19_Vaccines_03-15-21.xlsx)
[003_GA_COVID19_Vaccines_03-15-21.xlsx](https://github.com/GUI/covid-vaccine-spotter/files/6154220/003_GA_COVID19_Vaccines_03-15-21.xlsx)

**Comment by GUI** [comment]
Sorry for not circling back to this one sooner! I implemented Publix checking last week (https://github.com/GUI/covid-vaccine-spotter/commit/a5d91ddc0e162c41d3b9f8f7014df71b62161548). Publix appears to have changed their site, so the county-level text files are no longer being maintained, so it requires checking all the individual stores using the `rx.publix.com` endpoints. So apologies for the delay meaning things shifted, but the tips on the endpoints were useful, so thank you for getting all of this rolling, @bblack!

**Pull request closed without merging**
